### ISSUE TITLE
plottr.exe does not exist

### ISSUE THREAD

**Issue by RobertHenry6bev** [toolsforexperiments/plottr#15]
The README.md refers to a file plottr.exe which does not exist.  The docs should perhaps refer to plottr.py which contains __main__.  In any event, extensions .exe and .bat are meaningless on linux systems.

**Comment by jenshnielsen** [comment]
I am sorry but that is not correct they are not referring to the python files. The entry points are generated in the setup right here https://github.com/kouwenhovenlab/plottr/blob/master/setup.py#L15 and put on path as part of the install. That is standard python behavior. 

On windows these will be .exe files but you are right that on linux/osx they will probably just be `plottr` ect without any extension

**Comment by astafan8** [comment]
Indeed, @RobertHenry6bev, once you install the package, then those executables are generated automatically. This is one of the builtin features of python distribution/installation system. Thanks @jenshnielsen for responding to this!

@RobertHenry6bev , after you install `plottr` on linux/osx, can you just run `plottr` from the shell? I know for a fact that the `plottr.exe` file is generated on Windows and works OK.

Let know if you experience problems, otherwise I'll close the issue.
