### ISSUE TITLE
plottr doesn't run without pyqt5

### ISSUE THREAD

**Issue by FarBo** [toolsforexperiments/plottr#163]
I tried to install plottr in a fresh environment that qcodes was already installed there.
I couldn't run plottr-inspectr and this error returned:

`raise PythonQtError('No Qt bindings could be found') qtpy.PythonQtError: No Qt bindings could be found`

Then, I installed pyqt5 in the environment to be able to run the plottr.

Shouldn't pyqt5 to be a required package in the installation of plottr, if for any reason, qcodes doesn't install pyqt5 in the environment?

**Comment by jenshnielsen** [comment]
@FarBo plottr supports both Pyqt5 and Pyside. You can install either with `pip install plottr[PyQt5]`  or `pip instal plottr[PySide2]` 
Further more we want users to be able to install plottr in a conda environment. The conda pyqt package is called `pyqt` (note no 5) if you pip install pyqt5 on top of this package you will most likely break the environment since you will mix two different pyqt installs in the same env

**Comment by FarBo** [comment]
@jenshnielsen 
thanks for the response and It's fair. I close the issue.

**Comment by jenshnielsen** [comment]
Note that this is documented in https://github.com/toolsforexperiments/plottr#installation
