### ISSUE TITLE
Bilateral sweep setpoints

### ISSUE THREAD

**Issue by andreaiorio** [toolsforexperiments/plottr#222]
Hey, this is my first issue submission!
I'm interested in doing bilateral sweeps (let's say, back/forth IV curves), but the setpoints dependencies are not recognized correctly when saved in the way given by the example below.  

<img width="333" alt="Schermata 2021-09-13 alle 22 05 53" src="https://user-images.githubusercontent.com/17096757/133149228-010c33fc-a4ae-435a-9a3c-0c475bc52765.png">

```
from qcodes import Measurement

meas = Measurement()
meas.register_custom_parameter('s1')

meas.register_custom_parameter('y0_forth', setpoints=('s1',))
meas.register_custom_parameter('y0_back', setpoints=('s1',))

sweep = np.linspace(0,1,11)

with meas.run() as datasaver:
    dataid = datasaver.run_id
    
    for _s1 in sweep:
        datasaver.add_result(('s1', _s1),
                             ('y0_forth', _s1))
    
    for _s1 in sweep[::-1]:
        datasaver.add_result(('s1', _s1),
                             ('y0_back', _s1))                
```

**Comment by wpfff** [comment]
This is not so much a bug, but a situation that in general cannot be resolved. look at the data that qcodes acquired:
```
ds.get_parameter_data()

{'y0_back': {'y0_back': array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ]),
  's1': array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])},
 'y0_forth': {'y0_forth': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
  's1': array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])}} 
```

you have two arrays, both with name 's1', but they are not equal. That's a problem in general for plottr and it plays it safe here to prevent us from ending up with corrupted data so it renames one -- that's an easy fix because there's no logical dependency conflict here. you need some human insight to see that in this case you can actually sort them such that they can be mapped onto each other.
(Note: you'll see that also the export methods qcodes provide for pandas or xarray give warnings about this)

i'm open to suggestions on how detection of 'fixable' cases like this can be improved, but my first suggestion would be to improve the acquisition code.

**Comment by astafan8** [comment]
> my first suggestion would be to improve the acquisition code.

i agree with this, that would be my first instinct as well. would it make sense for this measurement to NOT create separate dependent parameters for up and down sweeps, and store them together? or, another idea, just make two separate datasets - you won't be able to plot them in plottr on the same window (right @wpfff ?) but e.g. in qcodes using `plot_dataset` that would be possible if axes are re-used.

**Comment by andreaiorio** [comment]
I agree with both of you but everything I tried has its pros and cons.
For instance:
1. storing everything in only one parameter (as suggested by @astafan8) would not work well for 2d maps
2. registering two parameter setpoints for s1 would not allow to plot the traces together in the same plot
3. saving the whole array with the back sweep flipped would miss the real-time plotting

Moreover option 2), when doing 2d maps, also gives me some issues in recognizing the setpoints while the measurement is running (see picture and code below). Of course both option 2) and 3) can work, but I'm not completely happy with both of them.
<img width="294" alt="Schermata 2021-09-14 alle 13 19 50" src="https://user-images.githubusercontent.com/17096757/133249167-9ad65baa-00fb-4edd-9460-ee26ce7527be.png">

```
import numpy as np
from qcodes import Measurement
rng = np.random.default_rng()

meas = Measurement()
meas.register_custom_parameter('s1_forth')
meas.register_custom_parameter('s1_back')
meas.register_custom_parameter('s2')

meas.register_custom_parameter('y0_forth', setpoints=('s1_forth','s2'))
meas.register_custom_parameter('y0_back', setpoints=('s1_back','s2'))
meas.register_custom_parameter('y1_forth', setpoints=('s1_forth','s2'))
meas.register_custom_parameter('y1_back', setpoints=('s1_back','s2'))

sweep_1 = np.linspace(0,1,11)
sweep_2 = np.linspace(0,10,11)

with meas.run() as datasaver:
    dataid = datasaver.run_id
    
    for _s2 in sweep_2:
        for _s1 in sweep_1:
            sleep(0.2)
            datasaver.add_result(('s1_forth', _s1),
                                 ('s2', _s2),
                                 ('y0_forth', _s1+rng.random()),
                                 ('y1_forth', _s1+rng.random()),)

        for _s1 in sweep_1[::-1]:
            sleep(0.2)
            datasaver.add_result(('s1_back', _s1),
                                 ('s2', _s2),
                                 ('y0_back', _s1-rng.random()),
                                 ('y1_back', _s1-rng.random()))
```

**Comment by wpfff** [comment]
I'm realizing that the issue you're facing also has a bit to do with how data is represented/loaded from the qcodes database. with plottr's own dataformat (which we're using in my lab and a few others), this problem does not actually occur, turns out.

for testing this you can run `plottr-monitr .` from your working directory to start the data browser.
the following snippet generates and saves data in hdf5 files with specific conventions (make sure to update plottr to the most recent version from github, though):

```
from time import sleep
import numpy as np
from plottr.data.datadict import str2dd, DataDict
from plottr.data.datadict_storage import DDH5Writer

sweep = np.linspace(0,11,11)

with DDH5Writer(
    str2dd("y0_forth(s1); y0_back(s1)"),
    name='Test measurement'
) as writer:
    
    for s in sweep:
        writer.add_data(
            s1=s,
            y0_forth=s**2 + np.random.normal(scale=1),
        )
        sleep(2)
        
    for s in sweep[::-1]:
        writer.add_data(
            s1=s,
            y0_back=s**2 + np.random.normal(scale=1),
        )
        sleep(2)
```

Notes: 
- To run this you need to update plottr -- i just had to fix a bug that was relevant and showed up due to a recent change in numpy, i believe. 
- the reason this behaves differently from the qcodes dataset is that the dataformat here explicitly saves everything as a single table: during the 'forth' sweep `None` is recorded by default for the 'back' data and vice versa. our dataformat deliberately demands that each addition of data must include all fields (even if data is `None` or `NaN`). conversely, when we process data in plottr we simply ignore all `None`/`NaN` type data during plotting.  In this specific case we have two traces that both contain a bunch of `NaNs` that simply don't show up when we plot.

**Comment by wpfff** [comment]
Looking at your most recent comment, though, i'm not sure that what i wrote will work for 2D maps for example -- probably will work when you create 2d scatter plots, but not with placing data on a grid (but i might be wrong :))

The issue here in general is really that you effectively operate with two different and what i'd call incompatible sets of data. The similarity between the different sets is such that i wouldn't know immediately how to find a generic routine that allows bringing them onto equal footing. a solution to this would probably have to enter in the data loading/selection step somewhere. happy to give feedback on any solution proposals ;)

**Comment by andreaiorio** [comment]
I understand, thanks for your time :) For now I decided to stick with saving the whole array at once after flipping it.

**Comment by wpfff** [comment]
ok, sounds good. i'm closing this for now then.
