### ISSUE TITLE
Improper display of 2D plots

### ISSUE THREAD

**Issue by jdwatson** [toolsforexperiments/plottr#29]
I ran plottr from the command line and tried viewing some old 2D datasets.  They open fine in the old version of plottr, but in the new version they only show up properly if I select 'no grid' and then zoom in on the data.  The top right plot window shows the output with 'no grid' selected.  I've also attached the db file with these 2D maps.

![image](https://user-images.githubusercontent.com/22443725/50979694-578f5680-14f7-11e9-95bb-03bfa37f71de.png)

[Extracted_runs.zip](https://github.com/kouwenhovenlab/plottr/files/2746044/Extracted_runs.zip)

**Comment by wpfff** [comment]
hey John, i'll look into the db, but quickly: how did you take the data? 
i haven't re-implemented the old gridding routine yet (but will soon). The new one will cause these kind of displays if you take data by say sweeping up/down rather than up/up (hope that's clear).

**Comment by jdwatson** [comment]
The data was taken with a pair of nested for loops like:
for vg in vgvals:
    set_vg(vg)
    for b in biasvals:
        set_b
        save data

**Comment by jdwatson** [comment]
ok, GitHub edited out the tabs in my comment above, but I think you probably get the picture.

**Comment by wpfff** [comment]
Hey @jdwatson -- that was an interesting one, that i probably should have foreseen. The issue was that I had assumed data usually to have the 'standard' ordering in grids, i.e., first axes is the slowest one, last axes the fast one -- that's the case where you can just use the standard np.reshape to restore the grid. 
your data did not conform to that, i.e., you specified the axes at measurement time the other way round, which is perfectly valid of course.

I've changed the way the grid is guessed now to be able to handle that properly. Your data looks fine for me now (pull should do it).

I'm closing it now -- there's some improvements that can be done, but the case is now supported (up to some tweaks that i need to put into the UI if one wanted to do specify the grid shape fully manually, see #33).

![image](https://user-images.githubusercontent.com/892193/51806781-7a9f6180-227e-11e9-8c44-d7c2dd09d110.png)
