### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by andreaiorio** [toolsforexperiments/plottr#48]
While launching the inspectr (from within the plottr root), I'm just getting the error:
```
File "apps/inspectr.py", line 15, in <module>
    from .. import log as plottrlog
ValueError: attempted relative import beyond top-level package
```
I'm using Python 3.6.8 in an Anaconda env. Am I missing something stupid (I'm new here!)?

**Comment by wpfff** [comment]
Hi Andrea,

i think you might be in the wrong directory :)
this error i can also reproduce when i'm in <base>/plottr/plottr, rather than <base>/plottr (theres a module in plottr/plottr/apps/inspectr.py, but the launching script is in plottr/apps/inspectr.py).

I might have chosen a bit of a confusing naming there... Let me know if that works.

**Comment by andreaiorio** [comment]
> Hi Andrea,
> 
> i think you might be in the wrong directory :)
> this error i can also reproduce when i'm in /plottr/plottr, rather than /plottr (theres a module in plottr/plottr/apps/inspectr.py, but the launching script is in plottr/apps/inspectr.py).
> 
> I might have chosen a bit of a confusing naming there... Let me know if that works.

Yes, I was confused by the launching script path! Thank you and sorry for the very stupid issue :-)
